# Generated by Django 5.0.6 on 2024-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="write_message",
            field=models.BooleanField(default=False, help_text="the user must write", verbose_name="write_message"),
        ),
    ]
