# Generated by Django 5.0.6 on 2024-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_mailing",
            field=models.BooleanField(default=False, help_text="select tg_mailing", verbose_name="tg_mailing"),
        ),
    ]
